package fi.iki.ede.safe.ui

enum class TestTag {
    TEST_TAG_BIOMETRICS_BUTTON,
    TEST_TAG_BIOMETRICS_CHECKBOX,
    TEST_TAG_CATEGORY_BUTTON,
    TEST_TAG_CATEGORY_MOVE_ROW,
    TEST_TAG_CATEGORY_ROW,
    TEST_TAG_CATEGORY_ROW_DELETE,
    TEST_TAG_CATEGORY_ROW_DELETE_CANCEL,
    TEST_TAG_CATEGORY_ROW_DELETE_CONFIRM,
    TEST_TAG_CATEGORY_ROW_EDIT,
    TEST_TAG_CATEGORY_TEXT_FIELD,
    TEST_TAG_HELP,
    TEST_TAG_LOGIN_BIOMETRICS_REGISTER,
    TEST_TAG_LOGIN_BIOMETRICS_VERIFY,
    TEST_TAG_LOGIN_BUTTON,
    TEST_TAG_PASSWORD_PROMPT,
    TEST_TAG_SEARCH_MATCH,
    TEST_TAG_SEARCH_TEXT_FIELD,
    TEST_TAG_TOP_ACTION_BAR_ADD,
    TEST_TAG_TOP_ACTION_BAR_SEARCH,
    TEST_TAG_PREFERENCES_SAVE_LOCATION,

    // TODO: move to extension function in TESTS
    TEST_TAG_PASSWORD_COMPOSABLE_IN_TESTS
}