plugins {
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.android.library) apply false
    alias(libs.plugins.android.dynamic.feature) apply false
    alias(libs.plugins.android.kotlin.multiplatform.library) apply false
    alias(libs.plugins.kotlin.multiplatform) apply false
    alias(libs.plugins.org.jetbrains.kotlin.android) apply false
    alias(libs.plugins.jetbrains.kotlin.jvm) apply false
    alias(libs.plugins.jetbrains.compose) apply false
    alias(libs.plugins.compose.compiler) apply false
    alias(libs.plugins.ksp) apply false
    alias(libs.plugins.room) apply false
    kotlin("plugin.serialization") version "2.4.0" apply false
    id("com.google.gms.google-services") version "4.4.4" apply false
    id("com.google.firebase.crashlytics") version "3.0.6" apply false
}

subprojects {
    val packageName = "fi.iki.ede.${project.name.replace("-", "")}"
    val outDir = layout.buildDirectory.dir("generated/buildconfig/commonMain/kotlin")

    val generateTask = tasks.register("generateBuildConfig") {
        outputs.dir(outDir)
        doLast {
            val file = outDir.get().asFile.resolve(packageName.replace('.', '/')).resolve("BuildConfig.kt")
            file.parentFile.mkdirs()
            file.writeText(
                """
                |// Generated by Gradle — do not edit.
                |package $packageName
                |
                |internal object BuildConfig {
                |    val DEBUG: Boolean = true
                |}
                """.trimMargin()
            )
        }
    }

    pluginManager.withPlugin("org.jetbrains.kotlin.multiplatform") {
        extensions.configure(org.jetbrains.kotlin.gradle.dsl.KotlinMultiplatformExtension::class.java) {
            sourceSets.getByName("commonMain").kotlin.srcDir(generateTask)
            
            targets.withType(com.android.build.api.dsl.KotlinMultiplatformAndroidLibraryTarget::class.java).configureEach {
                compileSdk = 37
                minSdk = 26
                androidResources {
                    @Suppress("UnstableApiUsage")
                    enable = true
                }
            }
        }
    }

    pluginManager.withPlugin("com.android.library") {
        extensions.configure(com.android.build.api.dsl.LibraryExtension::class.java) {
            compileSdk = 37
            defaultConfig.minSdk = 26
            androidResources {
                @Suppress("UnstableApiUsage")
                enable = true
            }
            buildFeatures {
                buildConfig = true
            }
        }
    }

    pluginManager.withPlugin("com.android.application") {
        extensions.configure(com.android.build.api.dsl.ApplicationExtension::class.java) {
            compileSdk = 37
            defaultConfig.minSdk = 26
            buildFeatures {
                buildConfig = true
            }
        }
    }
    
    pluginManager.withPlugin("com.android.dynamic-feature") {
        extensions.configure(com.android.build.api.dsl.DynamicFeatureExtension::class.java) {
            compileSdk = 37
            defaultConfig.minSdk = 26
            buildFeatures {
                buildConfig = true
            }
        }
    }
}
