package fi.iki.ede.safe.ui.composable

import androidx.compose.runtime.Composable
import platform.Foundation.NSLocale
import platform.Foundation.currentLocale
import platform.Foundation.languageCode

object IosResources {
    private val enStrings = mapOf(
        "action_bar_backup" to "Backup",
        "action_bar_backup_completed" to "Backup completed",
        "action_bar_change_master_password" to "Change master password",
        "action_bar_change_password_ok" to "Change the password!",
        "action_bar_generate_custom_password" to "Generate custom password",
        "action_bar_generate_password" to "Generate password",
        "action_bar_help" to "Help",
        "action_bar_import_export" to "Export&Import ▶",
        "action_bar_import_google_passwordmanager" to "Import GooglePassword manager",
        "action_bar_lock" to "Lock app",
        "action_bar_old_password" to "Enter current password",
        "action_bar_password_change_failed" to "Failed changing password!",
        "action_bar_password_changed" to "Master password changed!",
        "action_bar_restore" to "Restore",
        "action_bar_search" to "Search",
        "action_bar_settings" to "Settings",
        "action_bar_show_trash" to "Show trashcan",
        "application_name" to "Password Safe",
        "biometrics_authenticate_subtitle" to "Please authenticate yourself, or click cancel and enter the password. If you cancel, biometrics will be forgotten. You can easily re-enroll.",
        "biometrics_authenticate_title" to "Authentication required",
        "biometrics_authentication_error" to "ERROR: onAuthenticationError: %1\$d %2\$s",
        "biometrics_authentication_failed" to "ERROR: onAuthenticationFailed",
        "biometrics_cancel" to "Cancel",
        "biometrics_prompt_title" to "PasswordSafe Biometric",
        "biometrics_register" to "Register biometrics after successful login",
        "biometrics_register_subtitle" to "In order to bypass the password, biometrics need to be recorded. You can always cancel and fall back to password option. You can also turn off biometrics from settings later. You may be required to re-enroll biometrics periodically.",
        "biometrics_register_title" to "Registering new biometrics",
        "category_list_delete" to "Delete %s?",
        "category_list_delete_confirm" to "Are you sure you want to delete %s?",
        "category_list_edit" to "Edit category %s",
        "category_list_edit_category" to "Edit category name",
        "checkmark_description" to "Selected",
        "desktop_add_category" to "Add Category",
        "desktop_add_pass" to "Add Pass",
        "desktop_add_password_entry" to "Add Password Entry",
        "desktop_authenticating" to "Authenticating...",
        "desktop_backup_password" to "Backup Password",
        "desktop_backup_xml_file" to "Backup XML File",
        "desktop_bio_registered" to "Biometric credentials registered successfully",
        "desktop_biometric_auth_failed" to "Biometric authentication failed",
        "desktop_biometric_error" to "Biometric error: %1\$s",
        "desktop_biometric_unlock" to "Biometric Unlock",
        "desktop_browse" to "Browse",
        "desktop_category_name" to "Category Name",
        "desktop_create_vault_msg" to "Creating vault...",
        "desktop_delete_cat" to "Delete Cat",
        "desktop_enter_backup_password" to "Please enter backup password",
        "desktop_export_backup" to "Export Backup",
        "desktop_extension_type" to "Type",
        "desktop_extension_value" to "Value",
        "desktop_extensions" to "Extensions",
        "desktop_failed_create_vault" to "Failed to create vault: %1\$s",
        "desktop_file_not_exist" to "File does not exist",
        "desktop_import_backup_xml" to "Import Backup XML",
        "desktop_import_failed" to "Import failed: %1\$s",
        "desktop_no_biometric_key" to "No registered biometric key found",
        "desktop_password_entry_details" to "Password Entry Details",
        "desktop_scanning_fingerprint" to "Scanning fingerprint...",
        "desktop_select_backup_file" to "Please select a backup file",
        "desktop_unlock_success" to "Unlock successful! Logged in.",
        "desktop_unlock_success_biometric" to "Unlock successful! Logged in via biometrics.",
        "desktop_vault" to "Vault",
        "desktop_verifying_biometrics" to "Verifying biometrics...",
        "dropdown_description" to "Dropdown",
        "extension_preferences_add" to "Add",
        "extension_preferences_add_extension" to "Add Extension",
        "extension_preferences_apply" to "Apply",
        "extension_preferences_cancel" to "Cancel",
        "extension_preferences_delete" to "Delete",
        "extension_preferences_rename" to "Rename",
        "extension_type" to "Type",
        "extension_value" to "Value",
        "failed_to_create_vault" to "Failed to create vault",
        "generic_add" to "Add",
        "generic_cancel" to "Cancel",
        "generic_dont_delete" to "Don't delete!",
        "generic_ok" to "OK!",
        "generic_yes_delete" to "Do delete!",
        "google_password_links" to "Linked GPMs",
        "login_anew_button" to "Discard backup, start fresh",
        "login_anew_retry_button" to "Try login after all",
        "login_app_subtitle" to "Password Manager",
        "login_app_title" to "Safe",
        "login_button" to "Login",
        "login_button_clear_db" to "Login/Clear database",
        "login_choose_password_label" to "Choose Master Password",
        "login_confirm_password_label" to "Confirm Master Password",
        "login_create_vault_button" to "Create Vault",
        "login_export_backup_button" to "📤 Export Backup",
        "login_import_backup_button" to "📥 Import Backup",
        "login_invalid_password" to "Invalid password",
        "login_master_password_label" to "Master Password",
        "login_or_divider" to "OR",
        "login_password_tip" to "Enter your password",
        "login_screen_restore_mark_message" to "\"Looks like Google Automatic backup restored our data around %1\$s\"",
        "login_tip" to "Open with your password - or optionally with biometrics if you registered",
        "login_unlock_button" to "Unlock",
        "login_verify_password_tip" to "Enter the same password again",
        "login_with_biometrics" to "Login with biometrics",
        "move_password_cancel" to "Don't move",
        "move_password_confirm" to "Move!",
        "move_password_select_category" to "Select category to move to",
        "move_password_title" to "Move password to %1\$s",
        "notification_backup_reminder_description" to "You have some changes not backed up recently. Last backup was done %s. For your data safety, recommend doing backup soon. You can find backup and restore from top right corner menu in the PasswordSafe.",
        "notification_backup_reminder_title" to "Remember backup!",
        "notification_google_autobackup_description" to "Google automatic backup was done %s. If you uninstall and reinstall, your passwords are still safe. If you don't want this feature, you can turn it off from settings.",
        "notification_google_autobackup_quota_exceeded_description" to "Automatic backup quota exceeded %s. You can delete apps or their data from you Google Drive. You can continue making regular backups.",
        "notification_google_autobackup_quota_exceeded_title" to "Google Automatic Backup Quota Exceeded!",
        "notification_google_autobackup_title" to "Google autobackup done!",
        "notification_lock_description" to "Notification when password Safe is unlocked",
        "notification_lock_logged_in" to "Logged in",
        "notification_lock_title" to "Automatic locking",
        "password_entry_breach_check" to "Breach check",
        "password_entry_breached" to "This password has been breached",
        "password_entry_capture_photo" to "Take a photo",
        "password_entry_changed_date" to "Password last changed:",
        "password_entry_delete_photo" to "Delete photo",
        "password_entry_description_required" to "Description cannot be empty. You have to specify it (or discard changes).",
        "password_entry_description_tip" to "Enter description of the entry",
        "password_entry_discard" to "Discard",
        "password_entry_highlight_hint" to "Special coloring for numbers ",
        "password_entry_highlight_hint_l" to " lower case ",
        "password_entry_highlight_space" to "space",
        "password_entry_not_breached" to "This password has NOT been breached",
        "password_entry_note_tip" to "Notes about the entry",
        "password_entry_password_label" to "Copy",
        "password_entry_password_tip" to "Enter password",
        "password_entry_save" to "Save?",
        "password_entry_unsaved_changes_info" to "You have unsaved changes.\nWould you like to save or discard them?",
        "password_entry_username_label" to "Copy",
        "password_entry_username_tip" to "Enter username",
        "password_entry_visit" to "Visit",
        "password_entry_website_tip" to "Enter website, like https://…",
        "password_list_delete" to "Are you sure to delete the password %s?",
        "password_list_delete_password" to "Delete password %s",
        "password_list_move_password" to "Move password %s",
        "password_search_extensions" to "+Extensions",
        "password_search_notes" to "+Notes",
        "password_search_passwords" to "+Passwords",
        "password_search_search_hint" to "Find from descriptions",
        "password_search_usernames" to "+Usernames",
        "password_search_websites" to "+Websites",
        "preferences_autobackup_restore_finished" to "Google Automatic backups' restore finished",
        "preferences_autobackup_restore_started" to "Google Automatic backup was restored",
        "preferences_automatic_locking_selection_title" to "Choose automatic locking timeout",
        "preferences_clipboard_clear_delay_title" to "Clipboard clearing timeout",
        "preferences_edit_extensions" to "Edit Extensions",
        "preferences_experimental_features_title" to "Available Experimental Features",
        "preferences_summary_automatic_locking_timeout" to "After chosen amount of minutes, password safe will lock and require logging in again",
        "preferences_summary_clipboard_clear_delay" to "Delay in seconds after which clipboard is cleared",
        "preferences_summary_default_user_name" to "Default username when adding a new password. Completely optional, typically your email address.",
        "preferences_summary_enable_biometrics" to "Instead of password you can login with biometrics. Password fallback always available. Android will take care of actual biometric authenticatin. Password safe only receives information whether it succeeded or not. Even when enabled you may have to occasionally re-enroll for added security.",
        "preferences_summary_experimental_features" to "Some new feature may be tested by enabling them. There might be problems until they mature.",
        "preferences_summary_lastback_never_done" to "No backups yet",
        "preferences_summary_lock_when_screen_locks" to "When android screen lock turns on, password safe will automatically lock",
        "preferences_summary_soft_delete" to "%s. You can set a soft deletion time for passwords. If 0, they will be deleted immediately, if > 0, passwords marked deleted will be purged after this many days.",
        "preferences_title" to "Settings",
        "preferences_title_autobackup_quota_exceeded" to "Google Automatic backup quota exceeded",
        "preferences_title_autobackup_started" to "Google Automatic backup started(perhaps done)",
        "preferences_title_automatic_locking_timeout" to "Automatic locking timeout",
        "preferences_title_clipboard_clear_delay" to "Clipboard clearing delay",
        "preferences_title_default_backup_path" to "Default backup path",
        "preferences_title_default_user_name" to "Default username",
        "preferences_title_enable_biometrics" to "Enable biometric identification",
        "preferences_title_experimental_features" to "Experimental Features",
        "preferences_title_lock_when_screen_locks" to "Lock when screen locks",
        "preferences_title_make_a_crash" to "Make application crash",
        "preferences_title_soft_delete" to "Purge deleted passwords",
        "preferences_title_time_of_last_backup" to "Time of last backup",
        "remove_description" to "Remove",
        "restore_screen_backup_help" to "You need the password of the backup in order to restore it.\nBackup file %s",
        "restore_screen_backups_password" to "Enter backup's password",
        "restore_screen_begin_restore" to "Begin restoration, please wait",
        "restore_screen_categories_count" to "Categories %1\$d",
        "restore_screen_done" to "Done!",
        "restore_screen_finished_backup" to "Finished processing backup",
        "restore_screen_not_most_recent_backup" to "Not most recent backup file",
        "restore_screen_not_most_recent_backup_age" to "Backup is %1\$d days older than most recent (backup %2\$s vs latest %3\$s)",
        "restore_screen_not_most_recent_backup_cancel" to "Cancel!",
        "restore_screen_not_most_recent_backup_restore" to "Restore anyway!",
        "restore_screen_passwords_count" to "Passwords %1\$d",
        "restore_screen_process_backup" to "Processing backup...",
        "restore_screen_reread_database" to "Re-reading database...",
        "restore_screen_restore_button" to "Restore",
        "restore_screen_restore_failed" to "Restoration failed",
        "restore_screen_restored" to "Restoration complete: %1\$d",
        "restore_screen_restoring_old_backup" to "Restoring older backup...",
        "shortcut_backup_disabled" to "Cannot backup",
        "shortcut_backup_long" to "Make a backup",
        "shortcut_backup_short" to "Backup",
        "shortcut_search_disabled" to "Cannot search",
        "shortcut_search_long" to "Search for a password",
        "shortcut_search_short" to "Search",
        "site_entry_extension_cancel" to "Cancel",
        "site_entry_extension_collapsible" to "Extensions",
        "site_entry_extension_delete" to "Delete",
        "site_entry_extension_delete_message" to "Are you sure you want to delete this item?",
        "site_entry_extension_entry_label" to "Enter or select an item",
        "site_entry_generated_password" to "Generated password appears here",
        "site_entry_lowercases" to "Lower cases",
        "site_entry_numbers" to "Numbers",
        "site_entry_regenerate" to "Regenerate",
        "site_entry_uppercases" to "Upper cases",
        "title_activity_category_screen" to "Categories",
        "title_activity_help_screen" to "HelpScreen",
        "title_activity_password_entry_screen" to "PasswordEntryScreen",
        "title_activity_password_screen" to "PasswordScreen",
        "title_activity_password_search_screen" to "Password search",
        "title_activity_restore_screen" to "Restore passwords",
        "title_categorypager" to "Paged Category View",
        "title_hibp" to "HIBP support",
        "trash_cancel" to "Don't empty!",
        "trash_close" to "Close",
        "trash_do_empty" to "Good riddance!",
        "trash_empty_now" to "Really empty trash? It will be gone forever.",
        "trash_empty_trash" to "Empty!",
        "trash_restore" to "Restore!",
        "trash_title" to "Trashcan",
    )

    private val fiStrings = mapOf(
        "action_bar_backup" to "Varmuuskopio",
        "action_bar_backup_completed" to "Varmuuskopiointi valmis",
        "action_bar_change_master_password" to "Vaihda pääsalasana",
        "action_bar_change_password_ok" to "Vaihda salasana",
        "action_bar_generate_custom_password" to "Luo oma salasana",
        "action_bar_generate_password" to "Luo salasana",
        "action_bar_help" to "Apua",
        "action_bar_import_export" to "Palauta ja tuo ▶",
        "action_bar_import_google_passwordmanager" to "Tuo salasanat Google salasanamanagerista",
        "action_bar_lock" to "Lukitse",
        "action_bar_old_password" to "Syötä nykyinen salasana",
        "action_bar_password_change_failed" to "Salasanan vaihto epäonnistui!",
        "action_bar_password_changed" to "Pääsalasana vaihdettu!",
        "action_bar_restore" to "Palauta",
        "action_bar_search" to "Etsi",
        "action_bar_settings" to "Asetukset",
        "action_bar_show_trash" to "Näytä roskakori",
        "application_name" to "Password Safe",
        "biometrics_authenticate_subtitle" to "Please authenticate yourself, or click cancel and enter the password. If you cancel, biometrics will be forgotten. You can easily re-enroll.",
        "biometrics_authenticate_title" to "Tunnistautuminen vaaditaan",
        "biometrics_authentication_error" to "VIRHE: onAuthenticationError: %1\$d %2\$s",
        "biometrics_authentication_failed" to "VIRHE: onAuthenticationFailed",
        "biometrics_cancel" to "Peru",
        "biometrics_prompt_title" to "PasswordSafe biometriikka",
        "biometrics_register" to "Rekisteröi biometrinen tunniste onnistuneen sisäänkirjauksen jälkeen",
        "biometrics_register_subtitle" to "Ohittaaksei salasanan, biometriikka on tallennettava. Voit perua, salasanakirjautuminen toimii aina. Voit myös kytkeä biometriikan pois asetuksista myöhemmin. Biometriikka voidaan joutua rekisteröinään uudestaan ajoittain.",
        "biometrics_register_title" to "Rekisteröidään uusi biometriikka",
        "category_list_delete" to "Poista %s?",
        "category_list_delete_confirm" to "Haluatko varmasti poistaa %s?",
        "category_list_edit" to "Muokkaa kategoriaa %s",
        "category_list_edit_category" to "Muokkaa kategorian nimeä",
        "checkmark_description" to "Valittu",
        "desktop_add_category" to "Lisää kategoria",
        "desktop_add_pass" to "Lisää salasana",
        "desktop_add_password_entry" to "Lisää salasanamerkintä",
        "desktop_authenticating" to "Tunnistautuu...",
        "desktop_backup_password" to "Varmuuskopion salasana",
        "desktop_backup_xml_file" to "Varmuuskopio XML tiedosto",
        "desktop_bio_registered" to "Biometriset tunnukset rekisteröity onnistuneesti",
        "desktop_biometric_auth_failed" to "Biometrinen tunnistus epäonnistui",
        "desktop_biometric_error" to "Biometrinen virhe: %1\$s",
        "desktop_biometric_unlock" to "Biometrinen avaus",
        "desktop_browse" to "Selaa",
        "desktop_category_name" to "Kategorian nimi",
        "desktop_create_vault_msg" to "Luodaan holvia...",
        "desktop_delete_cat" to "Poista kategoria",
        "desktop_enter_backup_password" to "Syötä varmuuskopion salasana",
        "desktop_export_backup" to "Vie varmuuskopio",
        "desktop_extension_type" to "Tyyppi",
        "desktop_extension_value" to "Arvo",
        "desktop_extensions" to "Laajennukset",
        "desktop_failed_create_vault" to "Holvin luonti epäonnistui: %1\$s",
        "desktop_file_not_exist" to "Tiedostoa ei ole olemassa",
        "desktop_import_backup_xml" to "Tuo varmuuskopio XML",
        "desktop_import_failed" to "Tuonti epäonnistui: %1\$s",
        "desktop_no_biometric_key" to "Rekisteröityä biometristä avainta ei löytynyt",
        "desktop_password_entry_details" to "Salasanamerkinnän tiedot",
        "desktop_scanning_fingerprint" to "Luetaan sormenjälkeä...",
        "desktop_select_backup_file" to "Valitse varmuuskopiotiedosto",
        "desktop_unlock_success" to "Avaus onnistui! Kirjauduttu.",
        "desktop_unlock_success_biometric" to "Avaus onnistui! Kirjauduttu biometriikalla.",
        "desktop_vault" to "Holvi",
        "desktop_verifying_biometrics" to "Varmentaa biometriikkaa...",
        "dropdown_description" to "Pudotusvalikko",
        "extension_preferences_add" to "Lisää",
        "extension_preferences_add_extension" to "Lisää laajennus",
        "extension_preferences_apply" to "Tallenna",
        "extension_preferences_cancel" to "Peru",
        "extension_preferences_delete" to "Poista",
        "extension_preferences_rename" to "Nimeä",
        "extension_type" to "Tyyppi",
        "extension_value" to "Arvo",
        "failed_to_create_vault" to "Holvin luonti epäonnistui",
        "generic_add" to "Lisää",
        "generic_cancel" to "Peru",
        "generic_dont_delete" to "Älä poista!",
        "generic_ok" to "OK!",
        "generic_yes_delete" to "Poista!",
        "google_password_links" to "Linkitetyt GPM:T",
        "login_anew_button" to "Hylkää varmuuskopio, aloita alusta",
        "login_anew_retry_button" to "Kokeile kuitenkin perussisäänkirjausta",
        "login_app_subtitle" to "Salasanaholvi",
        "login_app_title" to "Safe",
        "login_button" to "Kirjaudu",
        "login_button_clear_db" to "Kirjaudu/Nollaa tietokanta",
        "login_choose_password_label" to "Valitse pääsalasana",
        "login_confirm_password_label" to "Vahvista pääsalasana",
        "login_create_vault_button" to "Luo holvi",
        "login_export_backup_button" to "📤 Vie varmuuskopio",
        "login_import_backup_button" to "📥 Tuo varmuuskopio",
        "login_invalid_password" to "Väärä salasana",
        "login_master_password_label" to "Pääsalasana",
        "login_or_divider" to "TAI",
        "login_password_tip" to "Syötä salasana",
        "login_screen_restore_mark_message" to "\"Näyttää että Googlen automaattisen varmuuskopion palautus tehtiin noin %1\$s\"",
        "login_tip" to "Avaa salasanalla tai biometriikalla",
        "login_unlock_button" to "Avaa lukitus",
        "login_verify_password_tip" to "Syötä sama salasana uudestaan",
        "login_with_biometrics" to "Kirjaudu biometriikalla",
        "move_password_cancel" to "Älä siirrä!",
        "move_password_confirm" to "Siirrä!",
        "move_password_select_category" to "Valitse kategoria mihin siirretään",
        "move_password_title" to "Siirrä salasana %1\$s",
        "notification_backup_reminder_description" to "Sinulla on varmuuskopioimattomia muutoksia! Edellinen varmuuskopio tehty %s. On suositeltavaa tehdä varmuuskopio pian. Varmuuskopioinnin ja palautuksen löydät PasswordSafen oikeassa ylänurkassa olevasta valikosta.",
        "notification_backup_reminder_title" to "Muista varmuuskopio!",
        "notification_google_autobackup_description" to "Googlen automaattinen varmuuskopiointi suoritettu %s. Jos poistat sovelluksen, ja asennat uudestaan nämä salasanat palautetaan automaattisesti. Voit kytkeä toiminnon pois asetuksista.",
        "notification_google_autobackup_quota_exceeded_description" to "Automaattisen varmuuskopioinnin tila on loppunut %s. Voit poistaa Google Driven asetuksista sovelluksia, tai niiden varmuuskopoita, jotta tilanne korjaantuu. Tavalliset itsetehdyt varmuuskopiot onnistuu aina.",
        "notification_google_autobackup_quota_exceeded_title" to "Googlen automaattisen varmuuskopioinnin tila on loppu!",
        "notification_google_autobackup_title" to "Googlen automaattinen varmuuskopio!",
        "notification_lock_description" to "Ilmoitus kun ohjelma on avattu",
        "notification_lock_logged_in" to "Kirjauduttu",
        "notification_lock_title" to "Automaattinen lukitus",
        "password_entry_breach_check" to "Tietomurtotarkistus",
        "password_entry_breached" to "Tämä salasana on paljastettu",
        "password_entry_capture_photo" to "Ota valokuva",
        "password_entry_changed_date" to "Salasana vaihdettu:",
        "password_entry_delete_photo" to "Poista kuva",
        "password_entry_description_required" to "Kuvaus pitää olla. Voit syöttää sen tai perua tallennuksen.",
        "password_entry_description_tip" to "Syötä kuvaus",
        "password_entry_discard" to "Hylkää",
        "password_entry_highlight_hint" to "Erikoisvärit numeroille",
        "password_entry_highlight_hint_l" to "\" pienaakkoset\"",
        "password_entry_highlight_space" to "välilyönti",
        "password_entry_not_breached" to "Tätä salasanaa ei ole murrettu",
        "password_entry_note_tip" to "Muistiinpanoja",
        "password_entry_password_label" to "Kopioi",
        "password_entry_password_tip" to "Syötä salasana",
        "password_entry_save" to "Tallenna",
        "password_entry_unsaved_changes_info" to "Sivulla on tallentamattomia muutoksia.\nHaluatko tallentaa vai hylätä ne?",
        "password_entry_username_label" to "Kopioi",
        "password_entry_username_tip" to "Syötä käyttäjänimi",
        "password_entry_visit" to "Mene",
        "password_entry_website_tip" to "Syötä webosoite, kuten https://",
        "password_list_delete" to "Poistetaanko salasana %s?",
        "password_list_delete_password" to "Poista salana %s",
        "password_list_move_password" to "Siirrä salana %s",
        "password_search_extensions" to "+Laajennukset",
        "password_search_notes" to "+Muistiinpanot",
        "password_search_passwords" to "+Salasanat",
        "password_search_search_hint" to "Etsi kuvauksista",
        "password_search_usernames" to "+Käyttäjänimet",
        "password_search_websites" to "+Webosoitteet",
        "preferences_autobackup_restore_finished" to "Google automaattisen varmuuskopion palautus päättyi",
        "preferences_autobackup_restore_started" to "Google automaattinen varmuuskopio palautettu",
        "preferences_automatic_locking_selection_title" to "Valitse automaattinen lukitusviive",
        "preferences_clipboard_clear_delay_title" to "Leikekirjan tyhjennysviive",
        "preferences_edit_extensions" to "Muokkaa laajennuksia",
        "preferences_experimental_features_title" to "Saatavilla olevat kokeelliset ominaisuudet",
        "preferences_summary_automatic_locking_timeout" to "Valitun viiveen jälkeen, ohjelma lukitsee itsensä ja vaatii sisäänkirjauksen",
        "preferences_summary_clipboard_clear_delay" to "Viive sekunneissa, jonka jälkeen leikekirja tyhjennetään",
        "preferences_summary_default_user_name" to "Oletuskäyttäjänimi kun lisätään uusi salasana. Valinnainen, yleensä sähkäpostiosoitteesi",
        "preferences_summary_enable_biometrics" to "Salasanan sijaan voit kirjautua biometriikalla. Salasanakirjaus on aina mahdollinen. Android järjestemä huolehtii biometriikan tallennuksesta ja varmennuksesta.",
        "preferences_summary_experimental_features" to "Täältä voi testata kokeellisia ominaisuuksia. Ne ei välttämättä toimi täydellisesti.",
        "preferences_summary_lastback_never_done" to "Ei varmuuskopioita",
        "preferences_summary_lock_when_screen_locks" to "Lukitse sovellus kun näyttö lukitaan",
        "preferences_summary_soft_delete" to "%s. Voit asettaa poistoajan salasanoille, jotka on merkattu poistettavaksi. Jos 0, salasanat tuhotaan heti, jos > 0, poistettavaksi merkatut salasanat tuhotaan näin monen päivän jälkeen.",
        "preferences_title" to "Asetukset",
        "preferences_title_autobackup_quota_exceeded" to "Googlen automaattisen varmuuskopioinnin tila loppui",
        "preferences_title_autobackup_started" to "Google automaattinen varmuuskopiointi alkoi (ja ehkä päättyi)",
        "preferences_title_automatic_locking_timeout" to "Automaattisen lukituksen viive",
        "preferences_title_clipboard_clear_delay" to "Leikekirjan tyhjennysviive",
        "preferences_title_default_backup_path" to "Oletusvarmuuskkopiopolku",
        "preferences_title_default_user_name" to "Oletuskäyttäjänimi",
        "preferences_title_enable_biometrics" to "Salli biometrinen tunnistautuminen",
        "preferences_title_experimental_features" to "Kokeelliset ominaisuudet",
        "preferences_title_lock_when_screen_locks" to "Lukitse kun näyttö lukitaan",
        "preferences_title_make_a_crash" to "Kaada sovellus",
        "preferences_title_soft_delete" to "Tuhoa poistetut salasanat",
        "preferences_title_time_of_last_backup" to "VIimeisen varmuuskopion aika",
        "remove_description" to "Poista",
        "restore_screen_backup_help" to "Palauttaksesi varmuuskopion, tarvitset sen salasanan. Varmuuskopio %s",
        "restore_screen_backups_password" to "Syötä varmuuskopion salasana",
        "restore_screen_begin_restore" to "Aloitetaan palautus, odota",
        "restore_screen_categories_count" to "Kategoriat %1\$d",
        "restore_screen_done" to "Valmis!",
        "restore_screen_finished_backup" to "Varmuuskopion käsittely valmis",
        "restore_screen_not_most_recent_backup" to "Tämä ei ole viimeisin varmuuskopio",
        "restore_screen_not_most_recent_backup_age" to "Varmuuskopio on %1\$d päivää vanhempi kuin viimeisin (tämä %2\$s vs viimeisin %3\$s)",
        "restore_screen_not_most_recent_backup_cancel" to "Peru!",
        "restore_screen_not_most_recent_backup_restore" to "Palauta silti!",
        "restore_screen_passwords_count" to "Salasanat %1\$d",
        "restore_screen_process_backup" to "Käsitellään varmuuskopiota...",
        "restore_screen_reread_database" to "Luetaan tietokantaa uudelleen...",
        "restore_screen_restore_button" to "Palauta",
        "restore_screen_restore_failed" to "Palautus epäonnistui",
        "restore_screen_restored" to "Palautus valmis %1\$d",
        "restore_screen_restoring_old_backup" to "Palautetaan vanhempaa varmuuskopiota...",
        "shortcut_backup_disabled" to "Varmuuskopiota ei voi tehdä",
        "shortcut_backup_long" to "Tee varmuuskopio",
        "shortcut_backup_short" to "Varmuuskopioi",
        "shortcut_search_disabled" to "Ei voi etsiä salasanaa",
        "shortcut_search_long" to "Etsi salasanaa",
        "shortcut_search_short" to "Etsi",
        "site_entry_extension_cancel" to "Peru",
        "site_entry_extension_collapsible" to "Laajennukset",
        "site_entry_extension_delete" to "Poista",
        "site_entry_extension_delete_message" to "Haluatko varmasti poistaa tämän?",
        "site_entry_extension_entry_label" to "Syötä tai valitse",
        "site_entry_generated_password" to "Luotu salasana ilmaantuu tähän",
        "site_entry_lowercases" to "Pienet kirjaimet",
        "site_entry_numbers" to "Numerot",
        "site_entry_regenerate" to "Luo uusi",
        "site_entry_uppercases" to "Isot kirjaimet",
        "title_activity_category_screen" to "Kategoriat",
        "title_activity_help_screen" to "Apunäyttö",
        "title_activity_password_entry_screen" to "Salasanan muokkausnäyttö",
        "title_activity_password_screen" to "Salasananäyttö",
        "title_activity_password_search_screen" to "Salasanan etsintä",
        "title_activity_restore_screen" to "Palauta salasanat",
        "title_categorypager" to "Sivutettu kategorianäyttö",
        "title_hibp" to "HIBP tuki",
        "trash_cancel" to "Älä tyhjennä!",
        "trash_close" to "Sulje",
        "trash_do_empty" to "Tervemenoa!",
        "trash_empty_now" to "Tyhjennetäänko roskakori? Peruuttamaton toimempide.",
        "trash_empty_trash" to "Tyhjennä!",
        "trash_restore" to "Palauta!",
        "trash_title" to "Roskakori",
    )

    private val enPlurals = mapOf(
        "category_passwords_count" to mapOf(
            "one" to "%d password",
            "other" to "%d passwords",
        ),
        "password_list_password_age_days" to mapOf(
            "one" to "%d day",
            "other" to "%d days",
            "zero" to "(brand new)",
        ),
        "password_list_password_age_months" to mapOf(
            "one" to "%d month",
            "other" to "%d months",
        ),
        "password_list_password_age_years" to mapOf(
            "one" to "%d year",
            "other" to "%d years",
        ),
        "preference_locktime" to mapOf(
            "few" to "%d minutes",
            "many" to "%d minutes",
            "one" to "%d minute",
            "other" to "%d minutes",
            "two" to "%d minutes",
        ),
        "site_entry_linked_gpms_count" to mapOf(
            "one" to "Has %1\$d linked GPM",
            "other" to "Has %1\$d linked GPMs",
        ),
    )

    private val fiPlurals = mapOf(
        "category_passwords_count" to mapOf(
            "one" to "%d salasana",
            "other" to "%d salasanaa",
        ),
        "site_entry_linked_gpms_count" to mapOf(
            "one" to "Linkitetty %1\$d GPM-tunnus",
            "other" to "Linkitetty %1\$d GPM-tunnusta",
        ),
    )

    private fun getLanguage(): String =
        NSLocale.currentLocale.languageCode

    fun getString(id: String): String {
        val lang = getLanguage()
        return if (lang == "fi") {
            fiStrings[id] ?: enStrings[id] ?: id
        } else {
            enStrings[id] ?: id
        }
    }

    fun getPluralString(id: String, quantity: Int): String {
        val lang = getLanguage()
        val quantityStr = when (quantity) {
            0 -> "zero"
            1 -> "one"
            2 -> "two"
            else -> "other"
        }
        val pluralsMap = if (lang == "fi") {
            fiPlurals[id] ?: enPlurals[id]
        } else {
            enPlurals[id]
        }
        return pluralsMap?.get(quantityStr) ?: pluralsMap?.get("other") ?: "%d $id"
    }
}

@Composable
actual fun getString(id: String): String = IosResources.getString(id)

@Composable
actual fun getString(id: String, formatArg: String): String =
    IosResources.getString(id).replace("%s", formatArg).replace("%1\$s", formatArg)

@Composable
actual fun getPluralString(id: String, quantity: Int, formatArg: Int): String =
    IosResources.getPluralString(id, quantity).replace("%d", formatArg.toString()).replace("%1\$d", formatArg.toString())
